CREATE TABLE `equipment_tender_applicationlll_sub` (
	`id` VARCHAR(32) NOT NULL COMMENT '主键',
	`company_id` VARCHAR(36) DEFAULT NULL COMMENT '公司id',
	`dr` INT(1) DEFAULT NULL COMMENT 'dr',
	`equipment_name` VARCHAR(50) DEFAULT NULL COMMENT '设备名称',
	`number` DECIMAL(100,0) DEFAULT NULL COMMENT '数量',
	`pid` VARCHAR(255) DEFAULT NULL COMMENT '主实体ID',
	`specification` VARCHAR(255) DEFAULT NULL COMMENT '规格型号',
	`tenantid` VARCHAR(36) DEFAULT NULL COMMENT '租户id',
	`ts` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '时间戳',
	`unit_price` DECIMAL(100,0) DEFAULT NULL COMMENT '单价',
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
